language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libjsoncpp-dev libzmq3-dev libboost-dev libboost-thread-dev libboost-system-dev libboost-filesystem-dev
script: "ci/travis-build.sh"
